CREATE TABLE PES (
                PES_CD_PESSOA NUMERIC(5) NOT NULL,
                PES_NM_PESSOA VARCHAR(60) NOT NULL,
                PES_ID_TIPPES CHAR(1) NOT NULL,
                PRIMARY KEY (PES_CD_PESSOA)
);

ALTER TABLE PES COMMENT 'TABELA PESSOA FISICA/JURIDICA';

ALTER TABLE PES MODIFY COLUMN PES_CD_PESSOA NUMERIC(5) COMMENT 'CÓDIGO DA PESSOA';

ALTER TABLE PES MODIFY COLUMN PES_NM_PESSOA VARCHAR(60) COMMENT 'NOME DA PESSOA';

ALTER TABLE PES MODIFY COLUMN PES_ID_TIPPES CHAR(1) COMMENT 'TIPO DE PESSOA
';


CREATE TABLE CNT (
                CNT_CD_CONTA NUMERIC(5) NOT NULL,
                CNT_VL_SALDO NUMERIC(8,2) DEFAULT 0 NOT NULL,
                CNT_TP_CONTA CHAR(1) NOT NULL,
                CNT_DT_VENCTO NUMERIC(8) NOT NULL,
                CNT_VL_LIMITE NUMERIC(8,2) NOT NULL,
                PRIMARY KEY (CNT_CD_CONTA)
);

ALTER TABLE CNT COMMENT 'TABELA CONTA';


CREATE TABLE MOV (
                MOV_CD_MOVTO NUMERIC(5) NOT NULL,
                MOV_DT_MOVTO NUMERIC(8) NOT NULL,
                MOV_TP_MOVTO CHAR(1) NOT NULL,
                MOV_VL_MOVTO NUMERIC(8,2) NOT NULL,
                MOV_CD_CONTA NUMERIC(5) NOT NULL,
                MOV_CD_CNTDST NUMERIC(5),
                PRIMARY KEY (MOV_CD_MOVTO)
);

ALTER TABLE MOV COMMENT 'TABELA DE MOVIMENTAÇÕES';

ALTER TABLE MOV MODIFY COLUMN MOV_DT_MOVTO NUMERIC(8) COMMENT 'DATA DO MOVIMENTO';

ALTER TABLE MOV MODIFY COLUMN MOV_TP_MOVTO CHAR(1) COMMENT 'IA';


CREATE TABLE LCT (
                LCT_CD_LANCTO NUMERIC(10) NOT NULL,
                LCT_DT_PAGVEN NUMERIC(8) NOT NULL,
                LCT_DT_LANCTO NUMERIC(8) NOT NULL,
                LCT_VL_LANCTO NUMERIC(8,2) NOT NULL,
                LCT_CD_CONTA NUMERIC(5) NOT NULL,
                LCT_NR_DOCLCT VARCHAR(30) NOT NULL,
                LCT_DS_LANCTO VARCHAR(60) NOT NULL,
                LCT_CD_PESSOA NUMERIC(5) NOT NULL,
                LCT_TP_LANCTO CHAR(1) NOT NULL,
                LCT_ID_SITUAC CHAR(1) NOT NULL,
                PRIMARY KEY (LCT_CD_LANCTO)
);

ALTER TABLE LCT COMMENT 'TABELA DE LANÇAMENTOS';

ALTER TABLE LCT MODIFY COLUMN LCT_DT_PAGVEN NUMERIC(8) COMMENT 'DATA DO PAGAMENTO/VENCIMENTO';

ALTER TABLE LCT MODIFY COLUMN LCT_DT_LANCTO NUMERIC(8) COMMENT 'DATA DO LANÇAMENTO';

ALTER TABLE LCT MODIFY COLUMN LCT_NR_DOCLCT VARCHAR(30) COMMENT 'NÚMERO DO DOCUMENTO';

ALTER TABLE LCT MODIFY COLUMN LCT_CD_PESSOA NUMERIC(5) COMMENT 'CÓDIGO DA PESSOA';

ALTER TABLE LCT MODIFY COLUMN LCT_TP_LANCTO CHAR(1) COMMENT 'TIPO DE LANÇAMENTO:
D - DESPESA
R - RECEITA';

ALTER TABLE LCT MODIFY COLUMN LCT_ID_SITUAC CHAR(1) COMMENT 'IDENTIFICAÇÃO DA SITUAÇÃO
PAGO
A PAGAR
RECEBIDO
A RECEBER';

/*
ALTER TABLE LCT ADD CONSTRAINT pes_lct_fk
FOREIGN KEY (LCT_CD_PESSOA)
REFERENCES PES (PES_CD_PESSOA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE LCT ADD CONSTRAINT cnt_lct_fk
FOREIGN KEY (LCT_CD_CONTA)
REFERENCES CNT (CNT_CD_CONTA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE MOV ADD CONSTRAINT cnt_mov_fk
FOREIGN KEY (MOV_CD_CONTA)
REFERENCES CNT (CNT_CD_CONTA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE MOV ADD CONSTRAINT cnt_mov_fk1
FOREIGN KEY (MOV_CD_CNTDST)
REFERENCES CNT (CNT_CD_CONTA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
*/